---
- name: Ensure that Nginx include directory exists
  file:
    path: "{{ nginx_include_dir }}"
    state: directory

- name: Copy phpMyAdmin Nginx configuration file
  template:
    src: templates/nginx-subfolder.conf.j2
    dest: "{{ nginx_include_dir }}/phpmyadmin.conf"
  notify: Reload Nginx
  when: phpmyadmin_http_server_mode == 'subfolder'

- name: Include phpMyAdmin Nginx configuration file
  blockinfile:
    path: "{{ nginx_default_conf_file }}"
    block: |4
        include {{ nginx_include_dir }}/phpmyadmin.conf;
    insertbefore: "}"
    marker: "\n# {mark} ANSIBLE MANAGED BLOCK"
  notify: Reload Nginx
