---
- name: Create the destination directory
  file:
    path: "{{ phpmyadmin_install_dir }}"
    state: directory

- name: Download and extract the PhpMyadmin archive
  unarchive:
    src: "{{ phpmyadmin_archive_url }}"
    dest: "{{ phpmyadmin_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
